### ISSUE TITLE
Can't use path as argument and sort at the same time

### ISSUE THREAD

**Issue by llagerlof** [madprops/lq#7]
When I use `lq /var` the contents of /var directory is displayed correctly.

When I use `lq -d` the contents os current directory is displayed correctly.

When I use `lq -d /var` or `lq /var -d` the prompt hangs.

**Comment by madprops** [comment]
`lq -d /var` works for me. Maybe your /var dir is huge? It has to check every file to get the directory date (since linux doesn't modify parent dir dates on inner file modifications afaik). 

![](http://i.imgur.com/Db33CM3.jpg)

**Comment by llagerlof** [comment]
I think I found the issue. Maybe.

My /var has 50000 files recursively, but the /var has only directories (22), and 133 files inside the first level of that directories.

`lq --tree /var` takes 29 seconds to run. 

`lq -d /var` takes 25 seconds to run.

Can I assume the `lq -d /var` is running full recursively, but showing me just the /var contents? In this case (without the --tree) can the program read only the first level of directories to take less time?

**Comment by madprops** [comment]
Yes. When checking directory dates it has to recursively check them, because there's no other way, at least with ext4, to get a directory's last modification date. So it checks all files and finds the most recent modification date. Maybe there's something I don't know about concerning this.

`can the program read only the first level of directories to take less time?` If you don't use -d it won't recursively check so it would be much faster. If you mean check only the first level of the directories inside the main path, then it wouldn't give accurate results.

Ideally each directory should have modification dates. Each file modification would bubble up and modify each parent dir. But as far as I know that's not the case with linux filesystems. 

But still maybe there's room for optimizations. Can you check a similar command that sorts /var by date? Unless they cache that information, they would be doing something better if the results are almost instant.

**Comment by llagerlof** [comment]
Ok, you are right. Even `ls -tl` uses the directory modification time, so now I understand. Your goal is sort the directories based on the last date of any children file or directory, doen't matter the level they are.

Well, it's a nice feature, and surely is very useful for many situations. I will use it here and there.

I am thinking on a daily basis, when most users sort by date to keep track the last changed files. If the `lq` always make a full recursive every time I use `-d`, won't be practical to use it in large directories every time.

I don't know if you will want to implement this, and I understand if you won't. What do you think to use the current `-d` behaviour as default, as you planned, but add an extra option to use the directory modification date instead of its children? eg:
`lq -d --use-directory-date /var` or something like that.

**Comment by madprops** [comment]
Yes you are right. I've been doing that distinction like, -z for file only size calculation and -Z for dir calculation, precisely for the efficiency reason. I forgot to do the same for sorting. So I just added these:

![](http://i.imgur.com/XU5H14w.png)

And since doing `-iI` or `-dD` can be too verbose I added these presets:

![](http://i.imgur.com/aGH3mGc.png)

**Comment by llagerlof** [comment]
Thank you very much. Now it's possible to `lq -d` all they way!

I just have a question. When using `lq -d` the directory listing is not sorted by directory modify date. Is this intentional? I am asking because `ls -t` uses the directory modify date to sort them.

**Comment by madprops** [comment]
Those aren't accurate modification dates. They're only dates where the directory itself got modified for some reason. For instance `docs` has been modified recently (the content inside), yet it says it was last modified in november. I could just use the dir metadata with those modification dates but they wouldn't be accurate to begin with, and i'd need to add yet another flag for "semi directory sort", because making a normal "-d" sort dirs like that is not following the "sort files (only)" approach.

![](http://i.imgur.com/fC22eCR.png)

**Comment by llagerlof** [comment]
Of course. But just in case the user runs -d (instead -D), isn't better to sort the directories by modification date instead of any sorting at all? Or this is out of scope?

You can even let the "sort files (only)" description, since these date are unreliable (but useful to quick find the last created directories).

**Comment by madprops** [comment]
What if you want to keep the alphabetical sorting on directories though?

**Comment by llagerlof** [comment]
Oh, I didn't realized the directories was in alphabetical order. In this case maybe an extra option to order the directories too? eg: `lq -dd ~/books` 

It's possible or will broke some other option?

**Comment by madprops** [comment]
Thing with short flags is that they can be combo'd. So `-dd` would be `d` twice. Though I could make some modifications on the argument system to get a usage count. I'll try that tomorrow.

**Comment by llagerlof** [comment]
Ok, but this was just an example. To not break the default behaviour of most linux commands, maybe use another letter? Or an extended option like `--sort-dir-by-date` or something like that.

**Comment by madprops** [comment]
I think it's a good idea, and shouldn't be a problem if restricted to on/off flags. I added a `count` property on the argument parser. Meaning I can now count how many times a flag was used. Which now allows to do:

![](http://i.imgur.com/U2nRurD.jpg)

**Comment by llagerlof** [comment]
Tests made, everything looking good. 

This was incredible. You are a fantastic developer.
